# Generated by Django 3.0 on 2019-12-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300, unique=True)),
                ('quantity', models.IntegerField(verbose_name='estoque atual')),
            ],
            options={
                'ordering': ('product',),
            },
        ),
    ]
